# Аттестация

### Задание 1.2

In [ ]:
a = [1,2,3]
b = a
c = [1,2,3]
print(a == b, a == c, a is b, a is c)

True True True False


### Задание 1.4

In [ ]:
one = [1, "2", 3, "4"]
two = ("a", "b", "c", "d")

In [ ]:
two.append('f')

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
one.extend(two)
print(one)
two.extend(one)

[1, '2', 3, '4', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']


AttributeError: 'tuple' object has no attribute 'extend'

In [ ]:
three = two + ('f', 'g')
print(three)
three_1 = one + two

('a', 'b', 'c', 'd', 'f', 'g')


TypeError: can only concatenate list (not "tuple") to list

### Задание 1.5

In [ ]:
my_lst = [1, 2, 3]
my_lst = my_lst[::-1]
my_lst.reverse()
print(my_lst)

[1, 2, 3]


### Задание 1.7

In [ ]:
my_dict = {'a': '1', 'c': '3', 'b': '2', 'd': '4'}
my_dict = sorted(my_dict.keys())
print(my_dict)

['a', 'b', 'c', 'd']


### Задание 1.8

In [ ]:
config = {
    "server": {
        "host": "127.0.0.1",
        "port": "22"
    },
    "configuration": {
        "ssh": {
            "access": True,
            "login": "some",
            "password": "some"
        },
        "name": "2491Oaaf1414"
    }
}

print(config['configuration']['ssh']['login'])

some


### Задание 1.9

In [ ]:
my_dict = {'a': '1', 'c': '3', 'b': '2', 'd': '4'}
key_list = []
value_list = []
for key, value in my_dict.items():
    key_list.append(key)
    value_list.append(value)

print(key_list)
print(value_list)

#Это было не нужно, просто я захотел вспомнить
sorted_my_dict = dict(sorted(my_dict.items(), key= lambda x: x[0]))
print(sorted_my_dict)

['a', 'c', 'b', 'd']
['1', '3', '2', '4']
{'a': '1', 'b': '2', 'c': '3', 'd': '4'}


### Задание 1.10

In [ ]:
s = 'I can do it !'
s = ''.join(s.split(' '))
print(s)

Icandoit!


In [ ]:
temperature = 98
remaining_time = 15
print(f'Температура: {temperature}, оставшееся время: {remaining_time}')
print('Температура: {}, оставшееся время: {}'.format(temperature, remaining_time))

Температура: 98, оставшееся время: 15
Температура: 98, оставшееся время: 15


### Задание 1.12

In [ ]:
s_2 = '1234'
s_2.isnumeric()
#Сделал неправильно, потому что поторопился и не проверил

True

### Задание 1.13

In [ ]:
car = 0
b = 4
while True:
    if car != b:
        car += 1
    else:
        break
    print(car)

1
2
3
4


### Задание 1.14

In [ ]:
for i in range(10, 181, 5):
    print(i)

10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180


### Задание 1.22

In [ ]:
import numpy as np

a = np.zeros((10, 10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Задание 2.1

In [ ]:
products = {'Oranges (packaged)': 114.99, 'Candy (Rotfront)': 280.0, 'Boiled sausage': 199.99, 'Juice J7 (orange)': 119.99, 'Trout (Seven Seas)': 399.99}
stocks = {'Boiled sausage': '33%', 'Juice J7 (orange)': '12%', 'Trout (Seven Seas)': '18%'}



def apply_discounts(products, stocks):
    discounted_products = {}
    for i in products.keys():
        if i not in stocks.keys():
            discounted_products[i] = products[i]
        else:
            fraction = float(stocks[i].replace('%', ''))/100
            discounted_products[i] = round(products[i] - products[i] * fraction, 2)
    return discounted_products
            
print(apply_discounts(products, stocks))



{'Oranges (packaged)': 114.99, 'Candy (Rotfront)': 280.0, 'Boiled sausage': 133.99, 'Juice J7 (orange)': 105.59, 'Trout (Seven Seas)': 327.99}


### Задание 2.2

# Практическое задание в Jupyter Notebook

In [ ]:
import pandas as pd
solar_data = pd.read_csv('data/solarpower.csv')
display(solar_data.head())
display(solar_data.info())

date  cum_power
0  2017-01-01    20111.0
1  2017-01-02    20112.0
2  2017-01-03    20115.0
3  2017-01-04    20117.0
4  2017-01-05    20119.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       664 non-null    object 
 1   cum_power  664 non-null    float64
dtypes: float64(1), object(1)
memory usage: 10.5+ KB


None

### Задание 3.1

In [ ]:
#Узнаем индексы пропусков
ind = solar_data[solar_data['cum_power'] == -1].index
print (ind)
repl_1 = ((solar_data['cum_power'].loc[46])+(solar_data['cum_power'].loc[44]))/2
print(repl_1)
solar_data['cum_power'].loc[45] = repl_1
ind = solar_data[solar_data['cum_power'] == -1].index
repl_2 =((solar_data['cum_power'].loc[648])+(solar_data['cum_power'].loc[646]))/2
print(repl_2)
solar_data['cum_power'].loc[647] = repl_2

Index([45, 647], dtype='int64')
20255.0
27998.0


C:\Users\Андрей\AppData\Local\Temp\ipykernel_8372\2009632296.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  solar_data['cum_power'].loc[45] = repl_1
C:\Users\Андрей\AppData\Local\Temp\ipykernel_8372\2009632296.py:6: SettingWithCopyWarni

In [188]:
display(round(solar_data['cum_power'].mean()))

23848

In [189]:
solar_data['day_power'] = solar_data['cum_power']
display(solar_data.head())

date  cum_power  day_power
0  2017-01-01    20111.0    20111.0
1  2017-01-02    20112.0    20112.0
2  2017-01-03    20115.0    20115.0
3  2017-01-04    20117.0    20117.0
4  2017-01-05    20119.0    20119.0

In [190]:
groped_solar_data = solar_data.copy()
display(groped_solar_data.head())

date  cum_power  day_power
0  2017-01-01    20111.0    20111.0
1  2017-01-02    20112.0    20112.0
2  2017-01-03    20115.0    20115.0
3  2017-01-04    20117.0    20117.0
4  2017-01-05    20119.0    20119.0

In [ ]:
groped_solar_data['date'] = pd.to_datetime(groped_solar_data['date'])
display(groped_solar_data.info())
display(groped_solar_data.head())
#Я запутался и не знаю дальше что делать. Я попрошу решение и решу это задание потом

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       664 non-null    datetime64[ns]
 1   cum_power  664 non-null    float64       
 2   day_power  664 non-null    float64       
dtypes: datetime64[ns](1), float64(2)
memory usage: 15.7 KB


None

date  cum_power  day_power
0 2017-01-01    20111.0    20111.0
1 2017-01-02    20112.0    20112.0
2 2017-01-03    20115.0    20115.0
3 2017-01-04    20117.0    20117.0
4 2017-01-05    20119.0    20119.0